name: Flutter application (Snapshot)

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # official action for cloning a repository with a lot of settings,

      - name: Install toolchain
        run: sudo apt-get update
             sudo apt-get install -y clang ninja-build libgtk-3-dev # package for install flutter in Ubuntu

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1 # unofficial action for downloading and installing Flutter SDK.
        with:
          flutter-version: "3.10.5"

      - name: Check Flutter installation
        run: flutter doctor

      - name: Get packages
        run: flutter pub get

      # - name: Run tests
      #   run: flutter test

      - name: Build application for Linux
        run: flutter build linux --debug
